datasektionen/bawang-content

namnder/dkm/body.md

Lägger till info om Reclaim, Plums & DPR

Mer info om DKMs event

---

naringsliv/d-dagen/body.md
naringsliv/d-dagen/meta.toml
naringsliv/d-dagen/sidebar.md

Plockar över D-Dagen sidan från purjo.

D-Dagen content

---

namnder/body.md
studier/studienamnden/body.md

Updated studienämnden structure and removed text saying SSO does not exist.

Updated stuff related to SSO

---

namnder/studienamnden/body.md
namnder/studienamnden/meta.toml

Only content is a link to /studier

Add Studienämnden

---

jumpfile.json
namnder/mottagningen/body.md
namnder/mottagningen/dadderiet/body.md
namnder/mottagningen/dadderiet/meta.toml
namnder/mottagningen/dadderiet/sidebar.md
namnder/mottagningen/doqumenteriet/body.md
namnder/mottagningen/doqumenteriet/meta.toml
namnder/mottagningen/doqumenteriet/sidebar.md
namnder/mottagningen/drifveriet/body.md
namnder/mottagningen/drifveriet/meta.toml
namnder/mottagningen/drifveriet/sidebar.md
namnder/mottagningen/ekonomeriet/body.md
namnder/mottagningen/ekonomeriet/meta.toml
namnder/mottagningen/ekonomeriet/sidebar.md
namnder/mottagningen/mammeriet/body.md
namnder/mottagningen/mammeriet/meta.toml
namnder/mottagningen/mammeriet/sidebar.md
namnder/mottagningen/sidebar.md

[SÖK](http://datasektionen.se/mottagningen/janifattar)

http://datasektionen.se/mottagningen/janifattar

---

organisation/sammansattning/body.md

Vilka kontaktfunkisar man har.

Uppdatera dreks sammansättning

---

namnder/datasektionens-musiknamnd/body.md
namnder/datasektionens-musiknamnd/sidebar.md
namnder/idrottsnamnden/sidebar.md
namnder/metadorerna/sidebar.md
namnder/valberedningen/body.md
namnder/valberedningen/meta.toml
namnder/valberedningen/sidebar.md

Gjorde maillänkarna i sidebaren till mailtos och snyggade till METAdorernas sidebar lite.
Fixade kontaktinfo på DEMON också

Fixade lite sidebars som såg off ut

---

namnder/qulturnamnden/sidebar.md
namnder/studienamnden/sidebar.md
namnder/tag-monkeys/sidebar.md

Uppdatera kontaktinfo

---

namnder/baknamnden/body.md
namnder/baknamnden/meta.toml
namnder/baknamnden/sidebar.md

Create page /namnder/baknamnden for Baknämnden.

Baknämnden woop

---

namnder/baknamnden/body.md
namnder/baknamnden/meta.toml
namnder/baknamnden/sidebar.md
sektionen/hedersdelta/body.md

Descriptions need to be added for the three receivers @Plongy

Put in hedersdelta for 2017

---

namnder/baknamnden/sidebar.md

Länken till Baknämndens facebooksida fungerade inte, fixade den.

Fix broken link to Facebook-page.

---

organisation/protokoll/body.md

Converted all dates to the same format

---

organisation/protokoll/body.md

Lägger till Extra-SM 2018

---

naringsliv/body.md
naringsliv/d-dagen/body.md
naringsliv/sidebar.md

Uppdaterade infon på näringslivssidan

---

en/clubs/informationsorganet/body.md

Uppdaterade till engelsk översättning

---

namnder/dkm/body.md

- Lade till sök-länk
- Tog tillbaka riktiga namn
- Tog tillbaka bilder

Tog bort mörkerläggning för DKM

---

en/body.md

(Making PR so it counts towards hacktoberfest)

Shorter title

---

en/industry/sidebar.md
naringsliv/sidebar.md

Uppdaterade näringsliv fb-länkar

---

en/contact/body.md

I am unsure on how to translate names, such as Näringslivsgruppen, and have named it "industry group" based on earlier translations. As well as "head of" for "-ansvarig".

Translation of Contact

---

en/organization/formalia/body.md

Translated titles and descriptions.

Translate formalia/body.md

---

namnder/studienamnden/body.md

Uppdaterade namnen för SN

---

namnder/studienamnden/body.md

Correct mail-address for SN

---

organisation/body.md

A new samboendeavtal was signed, so the link needed to be updated.

Update link to samboendeavtal

---

namnder/prylmangleriet/body.md

Förändringar från nytillträdde Prylis
Richard Lästh

Uppdatering av body för 2019

---

sektionen/hedersdelta/body.md

Shapour Jahanshahi was single recipient of the Honorary Delta 2019

Adds 2019 Honorary Delta recipients

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

I made a fork and made changes on it out of habit. I'm just gonna merge this.

Add minutes for Glögg-SM

---

organisation/protokoll/body.md

Lade till protokoll för ett regerings-DM, det är ett protokoll för ett DM från 2019

Lade till länk till Ett Regerings-DM

---

sektionen/val/body.md

Kassör saknades på den svenska sidan

Uppdatera urnvalsposter

---

en/clubs/geek/sidebar.md

Reverts datasektionen/bawang-content#162

Revert "Mörkläggning, men även fel namn"

---

en/organisation/arsrapporter/arsrapporter.md
en/organisation/arsrapporter/body.md
en/organisation/budget/body.md
en/organisation/protokoll/body.md

Reverts datasektionen/bawang-content#159

Revert "Hid info from english part of site"

---

en/clubs/mottagningen/drifveriet/body.md
en/clubs/mottagningen/drifveriet/meta.toml
en/clubs/mottagningen/drifveriet/sidebar.md
namnder/geek/sidebar.md
namnder/mottagningen/sidebar.md
organisation/arsrapporter/arsrapporter.md
organisation/budget/body.md
organisation/protokoll/body.md
sektionen/hedersdelta/body.md
sektionen/ordnar/body.md

Reverts datasektionen/bawang-content#143

Revert "Hemligheter"

---

namnder/dkm/body.md

Update body för DKM.md

---

organisation/verksamhetsplan/body.md

Lägg till verksamhetsplaner för vårbalen 2022 och metaspexet 2022
Beslutsuppföljning Budget-SM

add verksamhetsplaner

---

en/organisation/verksamhetsplan/body.md

Remove old projects from en + add forgotten ones

---

organisation/sammansattning/body.md

Continuation of #223 based on comments
Fixes a bit more of #181

Format email-addresses and add email subheaders

---

en/clubs/scala/body.md
en/clubs/scala/meta.toml
en/clubs/scala/sidebar.md
namnder/scala/body.md
namnder/scala/meta.toml
namnder/scala/sidebar.md

Noterade att scala inte hade blivit tillagd, så la till den

Add scala to nämnder

---

en/organisation/sammansattning/body.md

Add the vice treasure to the list of board members

Add vice treasurer

---

organisation/budget/body.md

Update Budget link

---

kontakt/body.md

Adds d-sys email alongside with ior on the contact page

Add d-sys email

---

en/clubs/internationellanamnden/body.md

Copy-pasted from the Swedish site.

Add info about the international club

---

en/organisation/budget/body.md

Update English budget page

---

organisation/protokoll/body.md

add beslutsprotokoll extra-sm 2022

---

en/chapter/hedersdelta/body.md

Uppdaterade formuläret på den engelska sidan för hedersdeltat till den för 2022. Samt la till 2020's mottagare av hedersdeltat på den engelska sidan.

Uppd eng hedersdelta form 2022

---

namnder/body.md
organisation/verksamhetsplan/body.md

Tagit bort Studs 2020 och dJulkalendern 2020 från hemsidan

21D10-01&21D10-02

---

organisation/krisplan/body.md

Update contact details and names of presidium/THS

---

namnder/karfullmaktige/body.md

The link to the KF at THS is broken. Replacing it with a working link.

fix broken KF link

---

sektionen/hedersdelta/body.md

Added the recipients of the Honorary Delta 2021

Honorary Delta 21

---

organisation/protokoll/body.md

Lägger till beslutsprotokoll för Ett-Olympiskt-DM 2022

add beslutsprotokoll dm 20220210

---

en/clubs/baknamnden/body.md
en/clubs/baknamnden/meta.toml
en/clubs/baknamnden/sidebar.md
namnder/baknamnden/body.md
namnder/baknamnden/sidebar.md

Uppdatera både baknämndens svenska och engelska sidor med relevant information och korrekta kontaktuppgifter.

Update baking pages

---

en/organisation/budget/body.md

- Fix Budget 2018 link
- Fix Budget 2019 link

Update expired links en

---

organisation/budget/body.md

- Update budget link for 2018
- Update budget link for 2019

Fix expired links

---

organisation/protokoll/body.md

Lade till beslutsprotokollet för Ett-Spontant-DM

---

organisation/protokoll/body.md

fix lägger till bindestreck mellan ett o spontant

---

jml/anmalan-och-fragor/body.md

Jag insåg att det saknades information om vart man kan vända sig om man inte vill använda det kommande formuläret, så jag lade till massa andra förslag på kontaktvägar

Update anmälningsvägar och kontaktinformation

---

jml/begreppslista/body.md

Det fattades ett gäng länkar som jag nu lagt till

Uppdaterade länkar

---

en/clubs/body.md
namnder/body.md

Adding the Spelsylt project to the site.

Add Spelsylt to list of projects

---

en/organisation/budget/body.md

Update Budget 2022 link

---

en/clubs/geek/body.md

Same as the swedish, we needed some upgrades. the info was in swedish and outdated.

Well needed update

---

namnder/body.md

Lade till <Placeholder> och Magenta

Lade till de nya projekten från rev-sm

---

namnder/geek/body.md

Alltså, det var dags. Informationen var utdaterad och tbh inte good enough.

En otroligt välbehövlig uppdatering

---

namnder/body.md

Plockar bort Vårbalken 2021 från öppna projekt på hemsidan.

22D03-02 Beslutsuppf. Plockar bort vårbalken 2021

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

Also added extra-SM to English page

Add rev-SM beslutsprotokoll

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

* translate some DMs on the english page
* add action minutes for latest dm

Update dm protocols

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

Consequentualise date formatting for protocols

---

en/chapter/hedersdelta/body.md
sektionen/hedersdelta/body.md

The physical awards has been handed out, so no it is time to put it up on the website

Honourary delta22

---

en/clubs/geek/meta.toml
namnder/geek/meta.toml

Vill ändra sidebaren men har honestly inte satt mig in i hur denna sida är uppbyggd pls help

Update Sidebar for Geek

---

en/clubs/qulturnamnden/sidebar.md
namnder/qulturnamnden/sidebar.md

Fix QA and QNO on both Swedish and English pages
Co-authored-by: Arvid Eriksson <arvid.f.eriksson@gmail.com>

Fix QA and add QNO

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

- Add diskussionsprotokoll for latest DM
- Fix missed translation
- Change translation of diskussionsprotokoll to be more consistent

Protocol fixing

---

en/clubs/auditors/body.md
en/clubs/auditors/meta.toml
en/clubs/auditors/sidebar.md
namnder/revisorer/body.md
namnder/revisorer/meta.toml
namnder/revisorer/sidebar.md

Added a page in both the swedish and english version for the Auditors.
- [x ] I have performed a self-review of my changes
- [ x] I have updated both Swedish and English pages (if not motivate why)

Revisor page

---

en/clubs/tag-monkeys/body.md

Nope, editar i webclienten och lyckas inte göra båda uppdateringarna på samma branch :)) Svensk version submittad på annan branch

Uppdaterad nämndinfo en

---

namnder/tag-monkeys/body.md

Nope, editar i webclienten och lyckas inte göra båda uppdateringarna på samma branch :)) Engelsk kommer på egen branch

Uppdatera nämndinfo

---

en/clubs/tag-monkeys/body.md

Sry for a bazillion branches, den andra som fortfarande är öppen har bara den svenska versionen
- [x ] I have performed a self-review of my changes
- [ x] I have updated both Swedish and English pages (if not motivate why)

Engelskt pet

---

en/clubs/Valberedningen/body.md
en/clubs/Valberedningen/sidebar.md
namnder/valberedningen/body.md
namnder/valberedningen/sidebar.md

Uppdatering av den svenska sidan samt skapande av den engelska
Skrev en bättre beskrivning och upptäckte det engelska språket

Uppdatering beskrivning Valberedningen

---

en/organisation/body.md
en/organisation/meta.toml

I was just upset about a few things on this page.

Oraganization -> Organisation

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

Add beslutsprotokoll for latest DM

---

namnder/body.md

The English page has a different structure

Update active projects

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

Add all remaining 2021 protocols

---

jml/anmalan-och-fragor/body.md
jml/anmalan-och-fragor/sidebar.md
jml/sidebar.md

Lägg till länkar till JML-systemet på hemsidan

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

Add action minutes for val-SM

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

Add discussion protcols for last 2 dms

---

jml/sidebar.md

Updatera drive-länk till google workspace istället för privat drive

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

Add beslutsprotokoll for extra-SM

---

en/clubs/geek/body.md

GEEK har som sagt nytt namn

---

en/clubs/geek/meta.toml

GEEK har bytt namn

---

namnder/geek/meta.toml

GEEK har bytt namn till Ada

---

namnder/geek/sidebar.md

Fel namn på titeln

---

namnder/jamlikhetsnamnden/sidebar.md

* Update name of current JNO
* Change d.kth mail to datasektionen mail

Update JNO and mail in sidebar

---

en/clubs/jamlikhetsnamnden/sidebar.md

Contact information for Jämlikhetsnämndens ordförande/Head of Equality Committee was added to sidebar

Add JNO contact info on sidebar

---

en/clubs/baknamnden/body.md
en/clubs/baknamnden/sidebar.md
namnder/baknamnden/sidebar.md

Uppdatera mejladress och länk till formulär (workspace).
Byt namn på Bakis på engelska (Bakie --> Baked).
- [ x] I have performed a self-review of my changes
- [ x] I have updated both Swedish and English pages (if not motivate why)

Baknämnden fippel

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

Add protocols that has been signed during the blackout, as well as the decision protocols from last 2 DMs.

Update protocol page

---

organisation/protokoll/body.md

fix protocol

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

Add discussion protocol for Ett-Ost-DM

---

en/clubs/demon/sidebar.md
namnder/datasektionens-musiknamnd/sidebar.md

Updated ärkedemon

---

en/organisation/sammansattning/body.md
organisation/sammansattning/body.md

- Updated members
- Moved contact info to be higher up on the page for each post
- Update functionary contacts

Update Drek page

---

en/clubs/Valberedningen/sidebar.md
namnder/valberedningen/sidebar.md

Uppdatera valberedare

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

Add protocol for Ett Heidrundrande DM.

Discussion protocol - Ett Heidrundrande DM

---

en/clubs/dkm/sidebar.md
namnder/dkm/sidebar.md

Change to sidebar of DKM to say applications are open

Andra ansökan till DKM

---

en/clubs/dkm/body.md
namnder/dkm/body.md

Change the displayed members of DKM to the current ones, and update the cliff list

ändra dkm medlemmar

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

Add the decision protocol for the latest SM

Add action minutes for Budget-SM

---

en/organisation/sammansattning/body.md
organisation/sammansattning/body.md

Update board members

---

en/organisation/verksamhetsplan/body.md
namnder/body.md
organisation/verksamhetsplan/body.md

Both add projects from latest SM and add some old that was missing

Update Operational plans

---

en/clubs/desc/sidebar.md
namnder/desc/sidebar.md

Korrigerade DESCtops mejladress samt engelska rubriker

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

Add discussion protocol for latest DM

---

namnder/metadorerna/sidebar.md

Update lokalchef SV

---

en/chapter/hedersdelta/body.md
sektionen/hedersdelta/body.md

Update hedersdelta link

---

en/clubs/dkm/body.md
namnder/dkm/body.md

I fucked up when i changed the DKM page last time. Added newlines.

Add newlines to DKM

---

en/clubs/dkm/body.md
namnder/dkm/body.md

Reverts datasektionen/bawang-content#360
Did not handle line breaks correctly.

Revert "Add newlines to DKM"

---

en/organisation/arsrapporter/body.md
organisation/arsrapporter/body.md

Lägg till årsrapport för 2021

---

en/clubs/datasladden/body.md
en/clubs/datasladden/meta.toml
en/clubs/datasladden/sidebar.md
namnder/datasladden/body.md
namnder/datasladden/meta.toml
namnder/datasladden/sidebar.md

Add Datasladden

---

en/clubs/jamlikhetsnamnden/meta.toml

Changed "Jämlikhetsnämnden" to "Equality Committee" on english website

Update JN en

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

Add decision protocol from last dm

Add decision protocol for ett batasco dm

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

Add diskussionsprotokoll for latest DM

---

en/clubs/jamlikhetsnamnden/body.md

Pontus, du var för snabb
Översatts JN:s text

Translate JN

---

en/clubs/dkm/sidebar.md
namnder/dkm/sidebar.md

Change the sidebar to not say DKM is currently not recruiting. (better late than never :))

Close dkm application

---

en/clubs/geek/body.md
en/clubs/geek/sidebar.md
namnder/geek/body.md
namnder/geek/sidebar.md

Updated info for Adas page, including relevant names and contact info.

Lallstedters patch 1

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

Beslutsprotokoll - glögg-SM

---

en/clubs/body.md
namnder/body.md

Remove closed projects

---

en/clubs/studienamnden/body.md
namnder/studienamnden/body.md
namnder/studienamnden/sidebar.md

Jag har ändrat så att studienämndens mejladdresser är uppdaterade samt att den svenska sidan stämmer överrens med den engelska. 
Jag har även uppdaterat så att funktionärsnamnen är korrekta. 
(Den svenska sidan var utdaterad)
Kommer nog förmodligen satsa på att ändra dessa så att de stämmer överrens med nya tillträdande funktionärer efter SM.

Fixade studienämndssidan

---

en/clubs/internationellanamnden/body.md
en/clubs/internationellanamnden/sidebar.md
namnder/internationella-namnden/body.md
namnder/internationella-namnden/sidebar.md

Update internationella nämnden

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

Diskussionsprotkoll DM-innan-Rev-SM

---

en/contact/body.md
en/organisation/sammansattning/body.md
organisation/sammansattning/body.md

Minor fixes

---

en/clubs/KF/sidebar.md
en/clubs/Valberedningen/sidebar.md
en/clubs/auditors/sidebar.md
en/clubs/baknamnden/sidebar.md
en/clubs/datasladden/sidebar.md
en/clubs/informationsorganet/sidebar.md
en/clubs/prylmangleriet/sidebar.md
en/clubs/scala/sidebar.md
en/clubs/stackoverbowl/body.md
en/clubs/stackoverbowl/meta.toml
en/clubs/studienamnden/body.md
en/clubs/tag-monkeys/sidebar.md
namnder/baknamnden/sidebar.md
namnder/datasladden/sidebar.md
namnder/informationsorganet/sidebar.md
namnder/karfullmaktige/sidebar.md
namnder/prylmangleriet/sidebar.md
namnder/revisorer/sidebar.md
namnder/scala/sidebar.md
namnder/studienamnden/body.md
namnder/tag-monkeys/sidebar.md
namnder/valberedningen/sidebar.md

Uppdatera funktionärer

---

en/clubs/datasladden/meta.toml
namnder/datasladden/meta.toml

Fixed Title on Datasladden

---

en/chapter/body.md

Fixed a minor typo. Changed the word 'Duscussion' to 'Discussion'.

Fix minor typo

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

@datasektionen/revisorer Note that Reset-DM was signed on the 12th of January, but just not uploaded until now since I lost yoggi access.

Add protocols for Ett Reset-DM and Glögg-SM

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

Lägg till beslutsprokoll

---

en/clubs/dkm/body.md
namnder/dkm/body.md

Updated dkm swedish and english page.

updated info DKM

---

en/chapter/lokalbokning/body.md
en/organisation/body.md
en/organisation/sidebar.md
organisation/body.md
sektionen/lokalbokning/body.md

Move cohabitation agreements to Drive

Move samboendeavtal to drive

---

en/organisation/sammansattning/body.md
organisation/sammansattning/body.md

Uppdatera D-reks medlemmar och lägga posterna i rätt ordning

Uppdatera D-rek medlemmar

---

en/organisation/protokoll/body.md
organisation/protokoll/body.md

Fix minute links

---

en/clubs/metadorerna/body.md
en/clubs/metadorerna/sidebar.md
namnder/metadorerna/body.md
namnder/metadorerna/sidebar.md

:)
[x] I have failed to do cherry-pick from the forked repository and therefore just copied files. embarrassing.

Update and Translate METAdorerna.

---

en/industry/body.md
naringsliv/body.md

Tog bort en onödig linje och fixade så att mejladressen blev en länk.

Småfix under Näringsliv

---

en/clubs/studienamnden/body.md
namnder/studienamnden/body.md

This PR updates information about student representatives as well as updates current trustees in the Study Board. It also adds the contact information for the machine learning master that does not have any representatives but still is our responsibility to look out for issues.

Updating Study Board information

---

sektionen/ordnar/body.md

Add Niklas Vatn to Ordförande Emeritus Orden

---

en/chapter/ordnar/body.md

Some general corrections as well

Add Niklas Vatn to English version of Ordförande Emeritus Orden

---

en/clubs/informationsorganet/body.md
namnder/informationsorganet/body.md

@lucubrator you can merge when you review.

fix: update ior slack links

---

en/chapter/ordnar/body.md
sektionen/ordnar/body.md

Add missing people as well as gender formatting for consistency. 
- [ x] I have performed a self-review of my changes
- [x ] I have updated both Swedish and English pages (if not motivate why)

Order in the orders

---

en/organisation/body.md
organisation/body.md

Update organisation map

---

en/clubs/body.md
namnder/body.md

23D07-06 Stängning Project Rebase

---

en/organisation/body.md
organisation/body.md

Make the organization chart link not have a date in it

---

en/clubs/body.md
namnder/body.md

23S03-12 Öppnar METAcraft

---

en/clubs/body.md
namnder/body.md

Lägger till länk till drive folder med alla verksamhetsplaner för öppna projekt

Lägger till länk till vp projekt folder

---

namnder/prylmangleriet/body.md

Update selling-weekday for prylmångleriet

---

en/clubs/body.md
namnder/body.md

23D06-01 Öppning av Project Pride 2024

---

en/clubs/informationsorganet/body.md
en/clubs/informationsorganet/sidebar.md
namnder/informationsorganet/body.md
namnder/informationsorganet/sidebar.md

Update information about IOR

---

en/clubs/body.md
namnder/body.md

Lägger till båda projekten (Project Dive och Groda 2024) som öppnades under Glögg-SM 2024 till svenska hemsidan.

23S04-11/23S04-16 Lägger till Dive och Groda till hemsidan

---

en/clubs/body.md
namnder/body.md

Closing of projects Metaspexet 2023 & Project Pride 2023.

23D102&3 - Closing of projects

---

en/clubs/body.md
namnder/body.md

23D11-5 Tar bort dÅre23

---

namnder/dkm/body.md

Jag har ändrat allt :D

---

en/chapter/dokument/body.md
sektionen/dokument/body.md

Added budget for 2024 on both english and swedish page
- [X ] I have performed a self-review of my changes
- [ X] I have updated both Swedish and English pages (if not motivate why)

Issue 488/budget2024

---

en/clubs/mottagningen/sidebar.md
namnder/mottagningen/sidebar.md

updated contact info

---

en/clubs/metadorerna/sidebar.md
namnder/metadorerna/body.md
namnder/metadorerna/sidebar.md

Och så lite annat småfix när man ändå håller på

Flytta ner metador-e-posten i hopp om färre mails

---

README.md
docker-compose.yml

Currently we have the problem that it is fairly hard to view changes you make to the content locally. This fixes this by adding a docker compose file that sets up all necessary systems locally and links them in the correct way.

Add docker compose to easily allow viewing changes locally

---

en/clubs/valberedningen/sidebar.md
namnder/valberedningen/sidebar.md

vb update vt24

---

docker-compose.yml

Fix le build

---

namnder/ovriga_funktionarer/body.md

La också till info om hur man bokar
Bytte namn på d-LoL från Filip Ramslöv (d-LoL emeritus) till Karl-Isac Åström (nuvarande invald d-LoL)
Adderade också info om var man bokar utrustning
Jag vet inte hur man gör så jag gör det två gånger (jag kommer inte bli utvecklare >:( )

Uppdatera namn på d-LoL

---

en/clubs/desc/sidebar.md
namnder/desc/sidebar.md

Update the name of the current DESCtop, which is now me.

Update DESCtop name

---

en/clubs/studienamnden/body.md
namnder/studienamnden/body.md

Update some age old incorrect information.

---

en/jml/sidebar.md
jml/sidebar.md

Added links to Uppförandepolicyn to the sidebar in the english and swedish pages for JML
- [x ] I have performed a self-review of my changes
- [x ] I have updated both Swedish and English pages (if not motivate why)

JNO lägger in Uppförandepolicyn på JMLsidan

---

en/clubs/internationellanamnden/body.md
namnder/internationella-namnden/body.md

Media has new Internationell Samordnare since their SM in March

newly elected Internationell Samordnare from Media

---

en/clubs/idrottsnamnden/body.md
namnder/idrottsnamnden/body.md

Lagt till information om tech-i-taka på hemsidan :)

Tech-i-taka

---

en/clubs/informationsorganet/sidebar.md
namnder/informationsorganet/sidebar.md

There can be only one Systemansvarig

---

en/clubs/idrottsnamnden/body.md
namnder/idrottsnamnden/body.md

Fix formatting on Tech-i-taka

---

en/clubs/ovriga_funktionarer/body.md
namnder/ovriga_funktionarer/body.md

Update names in ovriga funktionarer

---

en/chapter/hedersmedlem/body.md
sektionen/hedersmedlem/body.md

As two of our honorary members now have passed away they should be indicated as such.

Update deceased honorary members

---

en/chapter/sammansattning/body.md
sektionen/sammansattning/body.md

Reverts datasektionen/bawang-content#519
Doesn't work, so lets remove the broken image

Revert "D-rek-bild"

---

README.md

I guess we can call this a first draft

Rewrite darkmode documentation

---

en/clubs/studienamnden/body.md
namnder/studienamnden/body.md

Update dÅke year 2

---

en/chapter/organisation/body.md

PM for Economic

---

en/clubs/body.md
namnder/body.md

Fix le dAnka

---

en/clubs/datasladden/body.md
namnder/datasladden/body.md

Det heter Citroen, inte Citreon.

Det heter Citroen, inte Citreon

---

README.md
compose.yml

`compose.yml` is more general than `docker-compose.yml`. 
Should probably been a part of #554 
Can wait a bit with merge if someone else really wants commit 1337 :p

Rename compose file

---

namnder/ada/sidebar_en.md
namnder/ada/sidebar_sv.md
namnder/desc/sidebar_en.md
namnder/desc/sidebar_sv.md
namnder/gudar/sidebar_en.md
namnder/gudar/sidebar_sv.md
namnder/informationsorganet/sidebar_en.md
namnder/informationsorganet/sidebar_sv.md
namnder/metadorerna/sidebar_en.md
namnder/metadorerna/sidebar_sv.md
namnder/ovriga_funktionarer/body_en.md
namnder/ovriga_funktionarer/body_sv.md
namnder/qulturnamnden/sidebar_en.md
namnder/qulturnamnden/sidebar_sv.md
namnder/studienamnden/sidebar_en.md
namnder/studienamnden/sidebar_sv.md
namnder/studs/sidebar_en.md
namnder/studs/sidebar_sv.md
namnder/tag-monkeys/sidebar_en.md
namnder/tag-monkeys/sidebar_sv.md
namnder/valberedningen/sidebar_en.md
namnder/valberedningen/sidebar_sv.md

New chapter officials have been elected over the summer so this is just an update of names.

Update chapter officials

---

namnder/dare/body_en.md
namnder/dare/body_sv.md

Updated the information about dÅre

Kalle lindblad patch 1

---

namnder/studienamnden/body_en.md
namnder/studienamnden/body_sv.md

Updated page after recruitment

---

namnder/body_en.md
namnder/body_sv.md

Updaterade projektförtäckningen

Project fix

---

jml/begreppslista/body_sv.md
jml/sidebar_en.md
jml/sidebar_sv.md
namnder/informationsorganet/systemgruppen/body_en.md
namnder/informationsorganet/systemgruppen/body_sv.md
namnder/ovriga-funktionarer/body_en.md
namnder/ovriga-funktionarer/body_sv.md
sektionen/bokning/body_en.md
sektionen/bokning/body_sv.md
sektionen/organisation/sidebar_en.md

Many links to styrdokument were outdated. The reference to samboendeavtal in `sektionen/bokning` was outdated and I thought it's strange to just bring up a random point from samboendeavtalet here about the meeting room when other stuff is just as relevant.

Update styrdokument links

---

sektionen/sammansattning/body_en.md
sektionen/sammansattning/body_sv.md

new year new drek

---

namnder/informationsorganet/systemgruppen/sidebar_en.md
namnder/informationsorganet/systemgruppen/sidebar_sv.md

Yeet the Mathias guy

---

namnder/body_en.md
namnder/body_sv.md

Updated the Clubs page to accurately reflect the chapters currently open projects

Active projects update

---

namnder/eventorganet/ada/body_en.md
namnder/eventorganet/ada/body_sv.md
namnder/eventorganet/ada/sidebar_en.md

As requested by Stella Bobert.
Update list of members in Ada page

Update Ada members

---

kontakt/body_en.md
kontakt/body_sv.md

Kill old people and replace them with young and fresh ones.

Contact information updated

---

sektionen/sammansattning/body_en.md
sektionen/sammansattning/body_sv.md

I have managed to slay Vakant, hopefully for the last time.

kill vakant, replace with Carl

---

jml/anmalan-och-fragor/body_en.md
jml/anmalan-och-fragor/body_sv.md

Changed like a total of maybe 8 words to more accurately reflect the current world situation (Sofia Norlander is no longer vice Head, just Head and the board no longer receives all emails to their inbox but can still dig through and view all emails)

Update jml info regarding contact

---

namnder/informationsorganet/kommunikationsgruppen/body_en.md
namnder/informationsorganet/kommunikationsgruppen/body_sv.md
namnder/informationsorganet/kommunikationsgruppen/meta.toml
namnder/informationsorganet/kommunikationsgruppen/sidebar_en.md
namnder/informationsorganet/kommunikationsgruppen/sidebar_sv.md

Kommunikationsgruppen now exists and needs it's own page.

Add Kommunikationsgruppen to nämnder

---

namnder/ovriga-funktionarer/body_en.md
namnder/ovriga-funktionarer/body_sv.md

Remove Kommunikatör from "övriga funktionärer"

---

sektionen/ordnar/body_en.md
sektionen/ordnar/body_sv.md

- [ x] I have performed a self-review of my changes
- [ x] I have updated both Swedish and English pages (if not motivate why)

Ordnar 1ans 24

---

naringsliv/studs/sidebar_en.md
naringsliv/studs/sidebar_sv.md

I have updated the year and contact person for studs 2025

update contact person

---

namnder/ovriga-funktionarer/body_en.md
namnder/ovriga-funktionarer/body_sv.md
sektionen/dokument/body_en.md
sektionen/dokument/body_sv.md
sektionen/organisation/body_en.md
sektionen/organisation/body_sv.md
sektionen/organisation/sidebar_en.md
sektionen/organisation/sidebar_sv.md
sektionen/sidebar_en.md
sektionen/sidebar_sv.md

Fixed inconsistencies between Swedish & English in `sektionen/organisation`, updated auditors and added styrdokument to `sektionen/dokument`. The changes in `sektionen/organisation` are mostly just adding things written in one language but not the other, rearranging to look the same and fixing minor errors. Also adds styrdokument to the sidebar in `sektionen/`.

Organisation refurbishing

---

namnder/eventorganet/ada/meta.toml
namnder/eventorganet/dkm/meta.toml
namnder/eventorganet/internationella-namnden/meta.toml
namnder/forvaltningsorganet/metadorerna/meta.toml
namnder/informationsorganet/djulkalendern/meta.toml
namnder/informationsorganet/kommunikationsgruppen/meta.toml
namnder/informationsorganet/redaqtionen/meta.toml
namnder/informationsorganet/systemgruppen/meta.toml
namnder/mottagningen/meta.toml
namnder/naringslivsorganet/naringslivsgruppen/meta.toml
namnder/paverkansorganet/jamlikhetsnamnden/meta.toml
namnder/paverkansorganet/studienamnden/meta.toml
namnder/projekt/metaspexet/meta.toml
namnder/projekt/project-pride/meta.toml
namnder/projekt/studs/meta.toml
namnder/projekt/varbalen/meta.toml
namnder/studiesociala-organet/baknamnden/meta.toml
namnder/studiesociala-organet/demon/meta.toml
namnder/studiesociala-organet/desc/meta.toml
namnder/studiesociala-organet/prylmangleriet/meta.toml
namnder/studiesociala-organet/qulturnamnden/meta.toml
namnder/studiesociala-organet/scala/meta.toml
namnder/talmanspresidiet/meta.toml
namnder/valberedningen/meta.toml

Adds the logos of all committee's except Datasladden, GUDAR, dÅre & Idrottsnämnden who either don't have logos or are just missing from our drive.

Committee logos

---

sektionen/dokument/body_en.md
sektionen/dokument/body_sv.md

Toshihide sakao add budget 2025 link

---

sektionen/ordnar/body_en.md
sektionen/ordnar/body_sv.md

- [ x] I have performed a self-review of my changes
- [x ] I have updated both Swedish and English pages (if not motivate why)

Varbal24 orders

---

naringsliv/studs/body_en.md
naringsliv/studs/body_sv.md
naringsliv/studs/sidebar_en.md
naringsliv/studs/sidebar_sv.md

Add information about studs course

---

sektionen/dokument/body_en.md
sektionen/dokument/body_sv.md

Replace budget spreadsheets with GOrdian

---

sektionen/hedersmedlem/body_en.md
sektionen/hedersmedlem/body_sv.md

add new honourary members

---

namnder/valberedningen/sidebar_en.md
namnder/valberedningen/sidebar_sv.md

Update Valberedning info
